export const mockShadowghastRingResponse = {
    "Item": {
        "id": 178926,
        "description": "An exceptionally well crafted piece of jewelry worthy of being empowered by the Runecarver.",
        "name": "Shadowghast Ring",
        "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_jewelcrafting_90_maxlvlring_red.jpg",
        "buyPrice": 100,
        "equippable": true,
        "quality": 1,
        "sellPrice": 20,
        "itemSource": {},
        "hasSockets": false,
        "isAuctionable": true,
        "upgradable": false,
        "heroicTooltip": false,
        "bonusSummary": {},
        "IsVendored": false
    },
    "Quantity": 1,
    "AHPrice": 70000000,
    "BGPrice": 70000000,
    "BGRecommendation": "Buy",
    "MissingReason": "",
    "CheapestRecipe": {
        "SpellID": 327920,
        "RecipeName": "Shadowghast Ring",
        "ComponentPrice": 91438000,
        "RecipeMakes": 1,
        "Profession": "Jewelcrafting",
        "Components": [
            {
                "Item": {
                    "id": 173170,
                    "description": "Gathered by players with the Jewelcrafting skill. Most commonly found when prospecting Phaedrum Ore.",
                    "name": "Essence of Rebirth",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_jewelcrafting_90_reagent_green.jpg",
                    "buyPrice": 100000,
                    "equippable": false,
                    "quality": 2,
                    "sellPrice": 25000,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 10,
                "AHPrice": 36915000,
                "BGPrice": 36660000,
                "BGRecommendation": "Craft",
                "MissingReason": "",
                "CheapestRecipe": {
                    "SpellID": 311949,
                    "RecipeName": "Essence of Rebirth",
                    "ComponentPrice": 36660000,
                    "RecipeMakes": 1,
                    "Profession": "No Profession",
                    "Components": [
                        {
                            "Item": {
                                "id": 171831,
                                "description": "Gathered by players with the Mining skill. Can be bought and sold on the auction house.",
                                "name": "Phaedrum Ore",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_ore_phaedrite.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 2,
                                "sellPrice": 650,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 15,
                            "AHPrice": 3666000,
                            "BGPrice": 3666000,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        }
                    ],
                    "ProcModifier": false,
                    "CanBeMade": true
                }
            },
            {
                "Item": {
                    "id": 173171,
                    "description": "Gathered by players with the Jewelcrafting skill. Most commonly found when prospecting Sinvyr Ore.",
                    "name": "Essence of Torment",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_jewelcrafting_90_reagent_red.jpg",
                    "buyPrice": 100000,
                    "equippable": false,
                    "quality": 2,
                    "sellPrice": 25000,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 10,
                "AHPrice": 27400000,
                "BGPrice": 22065000,
                "BGRecommendation": "Craft",
                "MissingReason": "",
                "CheapestRecipe": {
                    "SpellID": 311949,
                    "RecipeName": "Essence of Torment",
                    "ComponentPrice": 22065000,
                    "RecipeMakes": 1,
                    "Profession": "No Profession",
                    "Components": [
                        {
                            "Item": {
                                "id": 171832,
                                "description": "Gathered by players with the Mining skill. Can be bought and sold on the auction house.",
                                "name": "Sinvyr Ore",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_ore_sinvyr.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 2,
                                "sellPrice": 650,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 15,
                            "AHPrice": 2206500,
                            "BGPrice": 2206500,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        }
                    ],
                    "ProcModifier": false,
                    "CanBeMade": true
                }
            },
            {
                "Item": {
                    "id": 178787,
                    "description": "",
                    "name": "Orboreal Shard",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_tradeskillitem_sorcererswind.jpg",
                    "buyPrice": 1250000,
                    "equippable": false,
                    "quality": 3,
                    "sellPrice": 312500,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": true
                },
                "Quantity": 10,
                "AHPrice": 12500000,
                "BGPrice": 12500000,
                "BGRecommendation": "Buy",
                "MissingReason": "",
                "CheapestRecipe": null
            },
            {
                "Item": {
                    "id": 171428,
                    "description": "Can be bought and sold on the auction house.",
                    "name": "Shadowghast Ingot",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_blacksmithing_craftedreagent_ingot.jpg",
                    "buyPrice": 50000,
                    "equippable": false,
                    "quality": 2,
                    "sellPrice": 12500,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Quantity": 20,
                "AHPrice": 25000000,
                "BGPrice": 20213000,
                "BGRecommendation": "Craft",
                "MissingReason": "",
                "CheapestRecipe": {
                    "SpellID": 307611,
                    "RecipeName": "Shadowghast Ingot",
                    "ComponentPrice": 20213000,
                    "RecipeMakes": 2,
                    "Profession": "Blacksmithing",
                    "Components": [
                        {
                            "Item": {
                                "id": 180733,
                                "description": "Used for removing impurities from metal. Sold by Blacksmithing vendors.",
                                "name": "Luminous Flux",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_misc_craftingreagent_flux01.jpg",
                                "buyPrice": 90000,
                                "equippable": false,
                                "quality": 1,
                                "sellPrice": 12500,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": true
                            },
                            "Quantity": 4,
                            "AHPrice": 360000,
                            "BGPrice": 360000,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        },
                        {
                            "Item": {
                                "id": 171830,
                                "description": "Gathered by players with the Mining skill. Can be bought and sold on the auction house.",
                                "name": "Oxxein Ore",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_ore_oxxein.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 2,
                                "sellPrice": 650,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 1,
                            "AHPrice": 400000,
                            "BGPrice": 400000,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        },
                        {
                            "Item": {
                                "id": 171831,
                                "description": "Gathered by players with the Mining skill. Can be bought and sold on the auction house.",
                                "name": "Phaedrum Ore",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_ore_phaedrite.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 2,
                                "sellPrice": 650,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 1,
                            "AHPrice": 244400,
                            "BGPrice": 244400,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        },
                        {
                            "Item": {
                                "id": 171832,
                                "description": "Gathered by players with the Mining skill. Can be bought and sold on the auction house.",
                                "name": "Sinvyr Ore",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_ore_sinvyr.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 2,
                                "sellPrice": 650,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 1,
                            "AHPrice": 147100,
                            "BGPrice": 147100,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        },
                        {
                            "Item": {
                                "id": 171829,
                                "description": "Gathered by players with the Mining skill. Can be bought and sold on the auction house.",
                                "name": "Solenium Ore",
                                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_ore_solenium.jpg",
                                "buyPrice": 25000,
                                "equippable": false,
                                "quality": 2,
                                "sellPrice": 650,
                                "itemSource": {},
                                "hasSockets": false,
                                "isAuctionable": true,
                                "upgradable": false,
                                "heroicTooltip": false,
                                "bonusSummary": {},
                                "IsVendored": false
                            },
                            "Quantity": 1,
                            "AHPrice": 869800,
                            "BGPrice": 869800,
                            "BGRecommendation": "Buy",
                            "MissingReason": "",
                            "CheapestRecipe": null
                        }
                    ],
                    "ProcModifier": false,
                    "CanBeMade": true
                }
            }
        ],
        "ProcModifier": false,
        "CanBeMade": true
    }
}

export const mockBountifulResponse = {
    "Message": "",
    "Data": {
        "Root": {
            "Item": {
                "id": 156526,
                "description": "",
                "name": "Bountiful Captain's Feast",
                "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_majorfeast.jpg",
                "buyPrice": 25000,
                "equippable": false,
                "quality": 1,
                "sellPrice": 1250,
                "itemSource": {},
                "hasSockets": false,
                "isAuctionable": true,
                "upgradable": false,
                "heroicTooltip": false,
                "bonusSummary": {},
                "IsVendored": false,
                "Rank": 0
            },
            "Quantity": 1,
            "AHPrice": 63558000,
            "BGPrice": 63558000,
            "BGRecommendation": "Buy",
            "MissingReason": "",
            "CheapestRecipe": {
                "SpellID": 259423,
                "RecipeName": "Bountiful Captain's Feast",
                "ComponentPrice": 14408950,
                "RecipeMakes": 1,
                "Profession": "Cooking",
                "Components": [
                    {
                        "Item": {
                            "id": 152545,
                            "description": "",
                            "name": "Frenzied Fangtooth",
                            "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_fishing_frenziedfangtooth.jpg",
                            "buyPrice": 25000,
                            "equippable": false,
                            "quality": 1,
                            "sellPrice": 625,
                            "itemSource": {},
                            "hasSockets": false,
                            "isAuctionable": true,
                            "upgradable": false,
                            "heroicTooltip": false,
                            "bonusSummary": {},
                            "IsVendored": false,
                            "Rank": 0
                        },
                        "Quantity": 15,
                        "AHPrice": 4095000,
                        "BGPrice": 4095000,
                        "BGRecommendation": "Buy",
                        "MissingReason": "",
                        "CheapestRecipe": null
                    },
                    {
                        "Item": {
                            "id": 154881,
                            "description": "",
                            "name": "Kul Tiramisu",
                            "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_kultiramisu.jpg",
                            "buyPrice": 25000,
                            "equippable": false,
                            "quality": 1,
                            "sellPrice": 1250,
                            "itemSource": {},
                            "hasSockets": false,
                            "isAuctionable": true,
                            "upgradable": false,
                            "heroicTooltip": false,
                            "bonusSummary": {},
                            "IsVendored": false,
                            "Rank": 0
                        },
                        "Quantity": 10,
                        "AHPrice": 2899000,
                        "BGPrice": 412850,
                        "BGRecommendation": "Craft",
                        "MissingReason": "",
                        "CheapestRecipe": {
                            "SpellID": 259413,
                            "RecipeName": "Kul Tiramisu",
                            "ComponentPrice": 412850,
                            "RecipeMakes": 10,
                            "Profession": "Cooking",
                            "Components": [
                                {
                                    "Item": {
                                        "id": 160711,
                                        "description": "",
                                        "name": "Aromatic Fish Oil",
                                        "icon": "https://render-us.worldofwarcraft.com/icons/56/trade_alchemy_dpotion_e2.jpg",
                                        "buyPrice": 25000,
                                        "equippable": false,
                                        "quality": 1,
                                        "sellPrice": 6250,
                                        "itemSource": {},
                                        "hasSockets": false,
                                        "isAuctionable": true,
                                        "upgradable": false,
                                        "heroicTooltip": false,
                                        "bonusSummary": {},
                                        "IsVendored": false,
                                        "Rank": 0
                                    },
                                    "Quantity": 2,
                                    "AHPrice": 40000,
                                    "BGPrice": 37600,
                                    "BGRecommendation": "Craft",
                                    "MissingReason": "",
                                    "CheapestRecipe": {
                                        "SpellID": 273293,
                                        "RecipeName": "Aromatic Fish Oil",
                                        "ComponentPrice": 37600,
                                        "RecipeMakes": 1,
                                        "Profession": "No Profession",
                                        "Components": [
                                            {
                                                "Item": {
                                                    "id": 152548,
                                                    "description": "",
                                                    "name": "Tiragarde Perch",
                                                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_fishing_tiragardeperch.jpg",
                                                    "buyPrice": 25000,
                                                    "equippable": false,
                                                    "quality": 1,
                                                    "sellPrice": 625,
                                                    "itemSource": {},
                                                    "hasSockets": false,
                                                    "isAuctionable": true,
                                                    "upgradable": false,
                                                    "heroicTooltip": false,
                                                    "bonusSummary": {},
                                                    "IsVendored": false,
                                                    "Rank": 0
                                                },
                                                "Quantity": 1,
                                                "AHPrice": 18800,
                                                "BGPrice": 18800,
                                                "BGRecommendation": "Buy",
                                                "MissingReason": "",
                                                "CheapestRecipe": null
                                            }
                                        ],
                                        "ProcModifier": false,
                                        "CanBeMade": true
                                    }
                                },
                                {
                                    "Item": {
                                        "id": 160400,
                                        "description": "",
                                        "name": "Foosaka",
                                        "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_foosaka.jpg",
                                        "buyPrice": 25000,
                                        "equippable": false,
                                        "quality": 1,
                                        "sellPrice": 625,
                                        "itemSource": {},
                                        "hasSockets": false,
                                        "isAuctionable": true,
                                        "upgradable": false,
                                        "heroicTooltip": false,
                                        "bonusSummary": {},
                                        "IsVendored": true,
                                        "Rank": 0
                                    },
                                    "Quantity": 5,
                                    "AHPrice": 125000,
                                    "BGPrice": 125000,
                                    "BGRecommendation": "Buy",
                                    "MissingReason": "",
                                    "CheapestRecipe": null
                                },
                                {
                                    "Item": {
                                        "id": 160705,
                                        "description": "For the adventurer with a sophisticated palate.",
                                        "name": "Major's Frothy Coffee",
                                        "icon": "https://render-us.worldofwarcraft.com/icons/56/spell_misc_drink.jpg",
                                        "buyPrice": 50,
                                        "equippable": false,
                                        "quality": 1,
                                        "sellPrice": 12,
                                        "itemSource": {},
                                        "hasSockets": false,
                                        "isAuctionable": true,
                                        "upgradable": false,
                                        "heroicTooltip": false,
                                        "bonusSummary": {},
                                        "IsVendored": true,
                                        "Rank": 0
                                    },
                                    "Quantity": 5,
                                    "AHPrice": 250,
                                    "BGPrice": 250,
                                    "BGRecommendation": "Buy",
                                    "MissingReason": "",
                                    "CheapestRecipe": null
                                },
                                {
                                    "Item": {
                                        "id": 160399,
                                        "description": "",
                                        "name": "Wild Flour",
                                        "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_wildflour.jpg",
                                        "buyPrice": 25000,
                                        "equippable": false,
                                        "quality": 1,
                                        "sellPrice": 625,
                                        "itemSource": {},
                                        "hasSockets": false,
                                        "isAuctionable": true,
                                        "upgradable": false,
                                        "heroicTooltip": false,
                                        "bonusSummary": {},
                                        "IsVendored": true,
                                        "Rank": 0
                                    },
                                    "Quantity": 10,
                                    "AHPrice": 250000,
                                    "BGPrice": 250000,
                                    "BGRecommendation": "Buy",
                                    "MissingReason": "",
                                    "CheapestRecipe": null
                                }
                            ],
                            "ProcModifier": false,
                            "CanBeMade": true
                        }
                    },
                    {
                        "Item": {
                            "id": 154898,
                            "description": "",
                            "name": "Meaty Haunch",
                            "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_meatyhaunch.jpg",
                            "buyPrice": 25000,
                            "equippable": false,
                            "quality": 1,
                            "sellPrice": 625,
                            "itemSource": {},
                            "hasSockets": false,
                            "isAuctionable": true,
                            "upgradable": false,
                            "heroicTooltip": false,
                            "bonusSummary": {},
                            "IsVendored": false,
                            "Rank": 0
                        },
                        "Quantity": 15,
                        "AHPrice": 1500000,
                        "BGPrice": 1500000,
                        "BGRecommendation": "Buy",
                        "MissingReason": "",
                        "CheapestRecipe": null
                    },
                    {
                        "Item": {
                            "id": 162515,
                            "description": "These fish are most prominent during the late hours of the day.",
                            "name": "Midnight Salmon",
                            "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_misc_fish_51.jpg",
                            "buyPrice": 25000,
                            "equippable": false,
                            "quality": 2,
                            "sellPrice": 625,
                            "itemSource": {},
                            "hasSockets": false,
                            "isAuctionable": true,
                            "upgradable": false,
                            "heroicTooltip": false,
                            "bonusSummary": {},
                            "IsVendored": false,
                            "Rank": 0
                        },
                        "Quantity": 2,
                        "AHPrice": 0,
                        "BGPrice": 0,
                        "BGRecommendation": "Buy",
                        "MissingReason": "noAuctions",
                        "CheapestRecipe": null
                    },
                    {
                        "Item": {
                            "id": 154885,
                            "description": "",
                            "name": "Mon'Dazi",
                            "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_mondazi.jpg",
                            "buyPrice": 25000,
                            "equippable": false,
                            "quality": 1,
                            "sellPrice": 1250,
                            "itemSource": {},
                            "hasSockets": false,
                            "isAuctionable": true,
                            "upgradable": false,
                            "heroicTooltip": false,
                            "bonusSummary": {},
                            "IsVendored": false,
                            "Rank": 0
                        },
                        "Quantity": 10,
                        "AHPrice": 1200000,
                        "BGPrice": 512600,
                        "BGRecommendation": "Craft",
                        "MissingReason": "",
                        "CheapestRecipe": {
                            "SpellID": 259444,
                            "RecipeName": "Mon'Dazi",
                            "ComponentPrice": 512600,
                            "RecipeMakes": 10,
                            "Profession": "Cooking",
                            "Components": [
                                {
                                    "Item": {
                                        "id": 160711,
                                        "description": "",
                                        "name": "Aromatic Fish Oil",
                                        "icon": "https://render-us.worldofwarcraft.com/icons/56/trade_alchemy_dpotion_e2.jpg",
                                        "buyPrice": 25000,
                                        "equippable": false,
                                        "quality": 1,
                                        "sellPrice": 6250,
                                        "itemSource": {},
                                        "hasSockets": false,
                                        "isAuctionable": true,
                                        "upgradable": false,
                                        "heroicTooltip": false,
                                        "bonusSummary": {},
                                        "IsVendored": false,
                                        "Rank": 0
                                    },
                                    "Quantity": 2,
                                    "AHPrice": 40000,
                                    "BGPrice": 37600,
                                    "BGRecommendation": "Craft",
                                    "MissingReason": "",
                                    "CheapestRecipe": {
                                        "SpellID": 273293,
                                        "RecipeName": "Aromatic Fish Oil",
                                        "ComponentPrice": 37600,
                                        "RecipeMakes": 1,
                                        "Profession": "No Profession",
                                        "Components": [
                                            {
                                                "Item": {
                                                    "id": 152548,
                                                    "description": "",
                                                    "name": "Tiragarde Perch",
                                                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_fishing_tiragardeperch.jpg",
                                                    "buyPrice": 25000,
                                                    "equippable": false,
                                                    "quality": 1,
                                                    "sellPrice": 625,
                                                    "itemSource": {},
                                                    "hasSockets": false,
                                                    "isAuctionable": true,
                                                    "upgradable": false,
                                                    "heroicTooltip": false,
                                                    "bonusSummary": {},
                                                    "IsVendored": false,
                                                    "Rank": 0
                                                },
                                                "Quantity": 1,
                                                "AHPrice": 18800,
                                                "BGPrice": 18800,
                                                "BGRecommendation": "Buy",
                                                "MissingReason": "",
                                                "CheapestRecipe": null
                                            }
                                        ],
                                        "ProcModifier": false,
                                        "CanBeMade": true
                                    }
                                },
                                {
                                    "Item": {
                                        "id": 160400,
                                        "description": "",
                                        "name": "Foosaka",
                                        "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_foosaka.jpg",
                                        "buyPrice": 25000,
                                        "equippable": false,
                                        "quality": 1,
                                        "sellPrice": 625,
                                        "itemSource": {},
                                        "hasSockets": false,
                                        "isAuctionable": true,
                                        "upgradable": false,
                                        "heroicTooltip": false,
                                        "bonusSummary": {},
                                        "IsVendored": true,
                                        "Rank": 0
                                    },
                                    "Quantity": 5,
                                    "AHPrice": 125000,
                                    "BGPrice": 125000,
                                    "BGRecommendation": "Buy",
                                    "MissingReason": "",
                                    "CheapestRecipe": null
                                },
                                {
                                    "Item": {
                                        "id": 160712,
                                        "description": "",
                                        "name": "Powdered Sugar",
                                        "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_powderedsugar.jpg",
                                        "buyPrice": 25000,
                                        "equippable": false,
                                        "quality": 1,
                                        "sellPrice": 625,
                                        "itemSource": {},
                                        "hasSockets": false,
                                        "isAuctionable": true,
                                        "upgradable": false,
                                        "heroicTooltip": false,
                                        "bonusSummary": {},
                                        "IsVendored": true,
                                        "Rank": 0
                                    },
                                    "Quantity": 4,
                                    "AHPrice": 100000,
                                    "BGPrice": 100000,
                                    "BGRecommendation": "Buy",
                                    "MissingReason": "",
                                    "CheapestRecipe": null
                                },
                                {
                                    "Item": {
                                        "id": 160399,
                                        "description": "",
                                        "name": "Wild Flour",
                                        "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_wildflour.jpg",
                                        "buyPrice": 25000,
                                        "equippable": false,
                                        "quality": 1,
                                        "sellPrice": 625,
                                        "itemSource": {},
                                        "hasSockets": false,
                                        "isAuctionable": true,
                                        "upgradable": false,
                                        "heroicTooltip": false,
                                        "bonusSummary": {},
                                        "IsVendored": true,
                                        "Rank": 0
                                    },
                                    "Quantity": 10,
                                    "AHPrice": 250000,
                                    "BGPrice": 250000,
                                    "BGRecommendation": "Buy",
                                    "MissingReason": "",
                                    "CheapestRecipe": null
                                }
                            ],
                            "ProcModifier": false,
                            "CanBeMade": true
                        }
                    },
                    {
                        "Item": {
                            "id": 152549,
                            "description": "",
                            "name": "Redtail Loach",
                            "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_fishing_redtailloach.jpg",
                            "buyPrice": 25000,
                            "equippable": false,
                            "quality": 1,
                            "sellPrice": 625,
                            "itemSource": {},
                            "hasSockets": false,
                            "isAuctionable": true,
                            "upgradable": false,
                            "heroicTooltip": false,
                            "bonusSummary": {},
                            "IsVendored": false,
                            "Rank": 0
                        },
                        "Quantity": 15,
                        "AHPrice": 1888500,
                        "BGPrice": 1888500,
                        "BGRecommendation": "Buy",
                        "MissingReason": "",
                        "CheapestRecipe": null
                    },
                    {
                        "Item": {
                            "id": 154897,
                            "description": "",
                            "name": "Stringy Loins",
                            "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_stringyloins.jpg",
                            "buyPrice": 25000,
                            "equippable": false,
                            "quality": 1,
                            "sellPrice": 625,
                            "itemSource": {},
                            "hasSockets": false,
                            "isAuctionable": true,
                            "upgradable": false,
                            "heroicTooltip": false,
                            "bonusSummary": {},
                            "IsVendored": false,
                            "Rank": 0
                        },
                        "Quantity": 15,
                        "AHPrice": 6000000,
                        "BGPrice": 6000000,
                        "BGRecommendation": "Buy",
                        "MissingReason": "",
                        "CheapestRecipe": null
                    }
                ],
                "ProcModifier": false,
                "CanBeMade": false
            }
        },
        "DataLastRefreshed": "2021-06-22T03:07:02Z",
        "Extended": false,
        "Realm": {
            "Realm": "arthas",
            "Region": "us",
            "GuildRealmID": 0
        },
        "BonusRank": {
            "ItemID": 156526,
            "RequestedBonusRank": 0,
            "ItemHasRanks": false
        }
    },
    "TotalRecords": 1
};

export const mockTruncatedResponse = {
    "Message": "",
    "Data": {
        "NumItemsQueried": 30,
        "DidTruncate": true,
        "TruncatedResults": [
            {
                "Item": {
                    "id": 7495,
                    "description": "",
                    "name": "Captain's Buckler",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_shield_10.jpg",
                    "buyPrice": 47793,
                    "equippable": true,
                    "quality": 2,
                    "sellPrice": 9558,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 3,
                "TotalQuantity": 3
            },
            {
                "Item": {
                    "id": 7488,
                    "description": "",
                    "name": "Captain's Circlet",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_crown_01.jpg",
                    "buyPrice": 35158,
                    "equippable": true,
                    "quality": 2,
                    "sellPrice": 7031,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 1,
                "TotalQuantity": 1
            },
            {
                "Item": {
                    "id": 163926,
                    "description": "",
                    "name": "Rusty Captain's Hook",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_hand_1h_piratehook_b_01.jpg",
                    "buyPrice": 3852421,
                    "equippable": true,
                    "quality": 3,
                    "sellPrice": 770484,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 1,
                "TotalQuantity": 1
            },
            {
                "Item": {
                    "id": 7486,
                    "description": "",
                    "name": "Captain's Breastplate",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_chest_plate07.jpg",
                    "buyPrice": 54401,
                    "equippable": true,
                    "quality": 2,
                    "sellPrice": 10880,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 1,
                "TotalQuantity": 1
            },
            {
                "Item": {
                    "id": 7487,
                    "description": "",
                    "name": "Captain's Leggings",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_pants_10.jpg",
                    "buyPrice": 50551,
                    "equippable": true,
                    "quality": 2,
                    "sellPrice": 10110,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 1,
                "TotalQuantity": 1
            },
            {
                "Item": {
                    "id": 7492,
                    "description": "",
                    "name": "Captain's Cloak",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_misc_cape_01.jpg",
                    "buyPrice": 26334,
                    "equippable": true,
                    "quality": 2,
                    "sellPrice": 5266,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 1,
                "TotalQuantity": 1
            },
            {
                "Item": {
                    "id": 164367,
                    "description": "",
                    "name": "Plundered Blue Captain's Hat",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_helm_cloth_pirate_b_01_blue.jpg",
                    "buyPrice": 12,
                    "equippable": true,
                    "quality": 2,
                    "sellPrice": 1,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 1,
                "TotalQuantity": 1
            },
            {
                "Item": {
                    "id": 164368,
                    "description": "",
                    "name": "Plundered Crimson Captain's Hat",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_helm_cloth_pirate_b_01_red.jpg",
                    "buyPrice": 12,
                    "equippable": true,
                    "quality": 2,
                    "sellPrice": 1,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 1,
                "TotalQuantity": 1
            },
            {
                "Item": {
                    "id": 7490,
                    "description": "",
                    "name": "Captain's Boots",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_boots_plate_09.jpg",
                    "buyPrice": 32928,
                    "equippable": true,
                    "quality": 2,
                    "sellPrice": 6585,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 1,
                "TotalQuantity": 1
            },
            {
                "Item": {
                    "id": 7489,
                    "description": "",
                    "name": "Captain's Gauntlets",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_gauntlets_04.jpg",
                    "buyPrice": 21946,
                    "equippable": true,
                    "quality": 2,
                    "sellPrice": 4389,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 1,
                "TotalQuantity": 1
            },
            {
                "Item": {
                    "id": 7491,
                    "description": "",
                    "name": "Captain's Shoulderguards",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_shoulder_18.jpg",
                    "buyPrice": 35697,
                    "equippable": true,
                    "quality": 2,
                    "sellPrice": 7139,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 1,
                "TotalQuantity": 1
            },
            {
                "Item": {
                    "id": 37811,
                    "description": "",
                    "name": "Captain Carver's Persuader",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_axe_81.jpg",
                    "buyPrice": 559914,
                    "equippable": true,
                    "quality": 3,
                    "sellPrice": 111982,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 1,
                "TotalQuantity": 1
            },
            {
                "Item": {
                    "id": 156526,
                    "description": "",
                    "name": "Bountiful Captain's Feast",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_cooking_80_majorfeast.jpg",
                    "buyPrice": 25000,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 1250,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 1,
                "TotalQuantity": 1
            },
            {
                "Item": {
                    "id": 21990,
                    "description": "Without these, or their captain, the Scarlet Onslaught won't be able to sail home!",
                    "name": "Netherweave Bandage",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_misc_bandage_netherweave.jpg",
                    "equippable": false,
                    "quality": 1,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 0,
                "TotalQuantity": 0
            },
            {
                "Item": {
                    "id": 34832,
                    "description": "",
                    "name": "Captain Rumsey's Lager",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_drink_03.jpg",
                    "buyPrice": 200,
                    "equippable": false,
                    "quality": 1,
                    "sellPrice": 50,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 0,
                "TotalQuantity": 0
            },
            {
                "Item": {
                    "id": 9249,
                    "description": "",
                    "name": "Captain's Key",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_misc_key_01.jpg",
                    "buyPrice": 6215,
                    "equippable": false,
                    "quality": 2,
                    "sellPrice": 1553,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 0,
                "TotalQuantity": 0
            },
            {
                "Item": {
                    "id": 7493,
                    "description": "",
                    "name": "Captain's Bracers",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_bracer_12.jpg",
                    "buyPrice": 19177,
                    "equippable": true,
                    "quality": 2,
                    "sellPrice": 3835,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 0,
                "TotalQuantity": 0
            },
            {
                "Item": {
                    "id": 122570,
                    "description": "Most of the log's pages are damaged, the writing ruined by the water. However, a few snippets of text here and there have survived.",
                    "name": "Captain's Log of the Queen's Reprisal",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_misc_book_14.jpg",
                    "equippable": false,
                    "quality": 1,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 0,
                "TotalQuantity": 0
            },
            {
                "Item": {
                    "id": 172042,
                    "description": "",
                    "name": "Surprisingly Palatable Feast",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_tradeskill_cooking_shadowlandsfeast_small01.jpg",
                    "equippable": false,
                    "quality": 1,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 0,
                "TotalQuantity": 0
            },
            {
                "Item": {
                    "id": 89603,
                    "description": "The log is written in a complex cipher - Nodd should be able to decode it.",
                    "name": "Encoded Captain's Log",
                    "icon": "https://render-us.worldofwarcraft.com/icons/56/inv_misc_book_12.jpg",
                    "equippable": false,
                    "quality": 1,
                    "itemSource": {},
                    "hasSockets": false,
                    "isAuctionable": true,
                    "upgradable": false,
                    "heroicTooltip": false,
                    "bonusSummary": {},
                    "IsVendored": false
                },
                "Rank": 0,
                "ActiveAuctions": 0,
                "TotalQuantity": 0
            }
        ]
    },
    "TotalRecords": 1
}